// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FooterCom: typeof import('./components/FooterCom/FooterCom.vue')['default']
    LoadingCom: typeof import('./components/Loading/LoadingCom.vue')['default']
    LoginDialog: typeof import('./components/LoginDialog/LoginDialog.vue')['default']
    LogoCom: typeof import('./components/LogoCom/LogoCom.vue')['default']
    NavBar: typeof import('./components/NavBar/NavBar.vue')['default']
    NoData: typeof import('./components/NoData/NoData.vue')['default']
    Pagination: typeof import('./components/Pagination/pagination.vue')['default']
    PreviewImage: typeof import('./components/PreviewImage/PreviewImage.vue')['default']
    ResumeBackgroundPopover: typeof import('./components/ResumeBackgroundPopover/ResumeBackgroundPopover.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkeletonCard: typeof import('./components/SkeletonCard/SkeletonCard.vue')['default']
    SvgIcon: typeof import('./components/SvgIcon/SvgIcon.vue')['default']
    TemplateCard: typeof import('./components/TemplateCard/TemplateCard.vue')['default']
    ZoomAndOut: typeof import('./components/ZoomAndOut/ZoomAndOut.vue')['default']
  }
}
